require: rubocop-rails

AllCops:
  Exclude:
    - 'app/controllers/application_controller.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EndOfLine:
  Enabled: false
  
Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120
